on:
  workflow_call:
    secrets:
      aws-access-key-id: 
        description: "SHR_S3_FLOWS_CI_ACCESS_KEY_ID stored in secrets manager"
        required: true 
      aws-secret-access-key: 
        description: "SHR_S3_FLOWS_CI_SECRET_ACCESS_KEY stored in secrets manager"
        required: true 

jobs:
  deploy_repo:
    name: Deploy archived nextflow workflow
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
    container:
      image: 654122908492.dkr.ecr.us-east-2.amazonaws.com/df_github_runner:0.0.4
      volumes: 
        - /resources/flows:/resources/flows

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Deploy to shr efs
      run: |
        # required to resolve 'dubious ownership' error in self-hosted runner
        git config --global --add safe.directory "*"

        # deploys the most recent tag
        tag=${{ github.ref_name }}
        dir=/resources/flows/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}/$tag
        mkdir $dir
        git archive --format=tar $tag | (cd $dir; tar -xvf -)
        chown -R 9000:9000 $dir
        chmod -R a+rX-w $dir
        cd $dir/.. && make-version-symlinks *
      
    - name: Sync efs to s3 for workflow
      run: |
        dir=/resources/flows/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
        cd $dir
        aws s3 sync ./ s3://myome-shr-flows/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}/ --delete --ignore-glacier-warnings
