on:
  workflow_call:
    inputs:
      efs_dir:
        required: false
        type: string
        default: ""

jobs:
  deploy_repo:
    name: Deploy archived repo
    runs-on: self-hosted
    container:
      image: 654122908492.dkr.ecr.us-east-2.amazonaws.com/df_github_runner:0.0.1
      volumes: 
        - /efs/${{ inputs.efs_dir }}:/efs/${{ inputs.efs_dir }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Deploy to shr efs
      run: |
        # required to resolve 'dubious ownership' error in self-hosted runner
        git config --global --add safe.directory "*"
        tag=${{ github.ref_name }}

        if [ "${{ inputs.efs_dir }}" = "flows" ]; then
          dir=/efs/${{ inputs.efs_dir }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}/$tag
          mkdir $dir
          git archive --format=tar $tag | (cd $dir; tar -xvf -)

        elif [ "${{ inputs.efs_dir }}" = "static-data" ]; then
          dir=/efs/${{ inputs.efs_dir }}/$tag
          mkdir $dir
          git archive --format=tar $tag | (cd $dir; tar --exclude-from=${OLDPWD}/.tar-excludes -xvf -)

        # elif [ "${{ inputs.efs_dir }}" = "schemas" ]; then
        #   dir=/efs/${{ inputs.efs_dir }}/$tag
        #   mkdir $dir
        #   git archive --format=tar $tag schemas | (cd $dir; tar --exclude-from=${OLDPWD}/.tar-excludes -xvf - --strip=1)
        #   symlink creation function here??
        fi

        # change ownership so directory can be accessed across accounts
        groupadd -g 9000 runner
        useradd -ms /bin/bash -g 9000 -u 9000 runner
        chown -R runner:runner $dir
        chmod -R a+rX-w $dir
