on:
  workflow_call:
    inputs:
      efs_dir:
        required: false
        type: string
        default: ""

jobs:
  deploy_repo:
    name: Deploy archived repo
    runs-on: self-hosted
    container:
      image: 654122908492.dkr.ecr.us-east-2.amazonaws.com/df_github_runner:0.0.4
      volumes: 
        - /myome/share/${{ inputs.efs_dir }}:/myome/share/${{ inputs.efs_dir }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Deploy to shr efs
      run: |
        # required to resolve 'dubious ownership' error in self-hosted runner
        git config --global --add safe.directory "*"

        # deploys the most recent tag that triggered this action
        make deploy-${{ github.ref_name }}
