on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: "workflow/nextflow_smoke_test.config"
      entry:
        required: false
        type: string
        default: "command_line"

defaults:
  run:
    shell: bash
    working-directory: nextflow

jobs:
 run_test:
   name: Smoke test
   runs-on: self-hosted
   container:
     image: 654122908492.dkr.ecr.us-east-2.amazonaws.com/df_github_runner:0.0.4
     volumes:
       - /root:/root
       - /usr/bin/docker:/usr/bin/docker
       - /resources/static-data:/myome/share/static-data
 
   steps:
   - name: Check out code
     uses: actions/checkout@v3
 
   - name: Inject slug/short variables
     uses: rlespinasse/github-slug-action@v3.x
 
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.SHR_S3_FLOWS_CI_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.SHR_S3_FLOWS_CI_SECRET_ACCESS_KEY }}
       aws-region: us-east-2
 
   - name: Login to Amazon ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v1
 
   - name: Run smoke test
     env:
       REPOSITORY: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
       LIMS_API_TOKEN: ${{ secrets.LIMS_API_TOKEN_STG }}
     run: |
       nextflow run workflow/${REPOSITORY}.nf \
       -entry ${{ inputs.entry }} \
       -c ${{ inputs.config }} \
       -params-file workflow/nextflow_shared.yaml \
       -w /root/actions-runner/_work/${REPOSITORY}/${REPOSITORY}/nextflow/
