on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    inputs:
      src:
        required: false
        type: string
        default: "./src"

name: Build and push to internal ECR
jobs:
  run_build_script:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Run build script (build_docker_image.sh)"
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo ${GITHUB_REF}
          ./build_docker_image.sh src=${{ inputs.src }} push=true backup=false
