on:
  workflow_call:
    inputs:
      py-version:
        required: false
        type: string
        default: "3.x"
    secrets:
      pypi-pw:
        description: "SHR_PYPI_CICD_UPLOAD_PWD stored in secrets manager"
        required: true
jobs:
  create_package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # https://github.com/pypa/setuptools_scm/issues/480
        with:
          fetch-depth: 0
      - name: Commit Info
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo ${GITHUB_REF}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  upload_package:
    name: Upload Package
    runs-on: ubuntu-latest
    needs: [create_package]
    env:
      PYPI_USER: github_cicd_uploader
      PYPI_PW: ${{ secrets.pypi-pw }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Copy Compiled file
        run: |
          twine upload --repository-url https://pypi.shr.myome.info/simple -u ${PYPI_USER} -p ${PYPI_PW} *
